WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
ORANGE = (255, 165, 0)

WIDTH = 800
HEIGHT = 450
FPS = 60
TITLE = 'Luminara - [DEVELOPMENT]'
BACKGROUND_COLOR = DARKGREY

ENEMY_SPEED = 4
# PLAYER_WIDTH = 32
# PLAYER_HEIGHT = 32
# PLAYER_HEALTH = 5
TILESIZE = 64
TILEWIDTH_HALF = TILESIZE//2
TILEHEIGHT_HALF = TILESIZE//2
SCROLLSPEED = 25

GRIDWIDTH = WIDTH // TILESIZE
GRIDHEIGHT = HEIGHT // TILESIZE

def move_x_up(x,y):
    return x+TILESIZE, y-TILEHEIGHT_HALF

def move_y_up(x,y):
    return x-TILESIZE, y-TILEHEIGHT_HALF

def move_x_down(x,y):
    return x+TILESIZE, y+TILEHEIGHT_HALF

def move_y_down(x,y):
    return x-TILESIZE, y+TILEHEIGHT_HALF